//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class BrowseProjects
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlBudget;
        protected global::System.Web.UI.WebControls.DropDownList ddlDate;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Label lblFilterMessage;
        protected global::System.Web.UI.WebControls.Panel pnlNoProjects;
        protected global::System.Web.UI.WebControls.Repeater rptProjects;
        protected global::System.Web.UI.WebControls.Panel pnlNoSelection;
        protected global::System.Web.UI.WebControls.Panel pnlProjectDetails;
        protected global::System.Web.UI.WebControls.Label lblPosted;
        protected global::System.Web.UI.WebControls.Label lblProjectTitle;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.Label lblBudget;
        protected global::System.Web.UI.WebControls.Label lblDeadline;
        protected global::System.Web.UI.WebControls.Label lblCategory;
        protected global::System.Web.UI.WebControls.Label lblExperience;
        protected global::System.Web.UI.WebControls.Label lblEmployerInitials;
        protected global::System.Web.UI.WebControls.Label lblEmployerName;
        protected global::System.Web.UI.WebControls.Label lblEmployerDetails;
        protected global::System.Web.UI.WebControls.Label lblEmployerRating;
        protected global::System.Web.UI.WebControls.Button btnSubmitProposal;
        protected global::System.Web.UI.WebControls.Button btnViewDetails;
        protected global::System.Web.UI.WebControls.Label lblProjectMessage;
    }
}
