//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class ChooseRole
    {
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlFreelancerActive;
        protected global::System.Web.UI.WebControls.Button btnContinueFreelancer;
        protected global::System.Web.UI.WebControls.Panel pnlFreelancerDeactivated;
        protected global::System.Web.UI.WebControls.Button btnReactivateFreelancer;
        protected global::System.Web.UI.WebControls.Panel pnlFreelancerNotCreated;
        protected global::System.Web.UI.WebControls.Button btnCreateFreelancer;
        protected global::System.Web.UI.WebControls.Panel pnlEmployerActive;
        protected global::System.Web.UI.WebControls.Button btnContinueEmployer;
        protected global::System.Web.UI.WebControls.Panel pnlEmployerDeactivated;
        protected global::System.Web.UI.WebControls.Button btnReactivateEmployer;
        protected global::System.Web.UI.WebControls.Panel pnlEmployerNotCreated;
        protected global::System.Web.UI.WebControls.Button btnCreateEmployer;
        protected global::System.Web.UI.WebControls.Panel pnlCreateFreelancer;
        protected global::System.Web.UI.WebControls.TextBox txtSkills;
        protected global::System.Web.UI.WebControls.TextBox txtExperience;
        protected global::System.Web.UI.WebControls.TextBox txtPortfolio;
        protected global::System.Web.UI.WebControls.TextBox txtHourlyRate;
        protected global::System.Web.UI.WebControls.Button btnSubmitFreelancer;
        protected global::System.Web.UI.WebControls.Button btnCancelFreelancer;
        protected global::System.Web.UI.WebControls.Panel pnlCreateEmployer;
        protected global::System.Web.UI.WebControls.TextBox txtCompanyName;
        protected global::System.Web.UI.WebControls.DropDownList ddlIndustry;
        protected global::System.Web.UI.WebControls.TextBox txtContactEmail;
        protected global::System.Web.UI.WebControls.TextBox txtCompanyDesc;
        protected global::System.Web.UI.WebControls.Button btnSubmitEmployer;
        protected global::System.Web.UI.WebControls.Button btnCancelEmployer;
    }
}
