//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class CreateFreelancerProfile
    {
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.FileUpload fuProfilePic;
        protected global::System.Web.UI.WebControls.TextBox txtBio;
        protected global::System.Web.UI.WebControls.TextBox txtLocation;
        protected global::System.Web.UI.WebControls.DropDownList ddlLanguage;
        protected global::System.Web.UI.WebControls.TextBox txtSkills;
        protected global::System.Web.UI.WebControls.TextBox txtExperience;
        protected global::System.Web.UI.WebControls.TextBox txtPortfolio;
        protected global::System.Web.UI.WebControls.TextBox txtHourlyRate;
        protected global::System.Web.UI.WebControls.FileUpload fuProfilePicture;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
