//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class CreateEmployerProfile
    {
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.FileUpload fuProfilePic;
        protected global::System.Web.UI.WebControls.TextBox txtBio;
        protected global::System.Web.UI.WebControls.TextBox txtLocation;
        protected global::System.Web.UI.WebControls.DropDownList ddlLanguage;
        protected global::System.Web.UI.WebControls.TextBox txtCompanyName;
        protected global::System.Web.UI.WebControls.DropDownList ddlIndustry;
        protected global::System.Web.UI.WebControls.TextBox txtContactEmail;
        protected global::System.Web.UI.WebControls.TextBox txtCompanyDesc;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
