//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Literal litFirstName;
        protected global::System.Web.UI.WebControls.Literal litRole;
        protected global::System.Web.UI.WebControls.Literal litRating;
        protected global::System.Web.UI.WebControls.Literal litProjectsLabel;
        protected global::System.Web.UI.WebControls.Literal litProjectsCount;
        protected global::System.Web.UI.WebControls.Literal litProposalsLabel;
        protected global::System.Web.UI.WebControls.Literal litProposalsCount;
        protected global::System.Web.UI.WebControls.Literal litBalance;
        protected global::System.Web.UI.WebControls.Panel pnlFreelancerActions;
        protected global::System.Web.UI.WebControls.Panel pnlEmployerActions;
        protected global::System.Web.UI.WebControls.Repeater rptActivity;
        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;
    }
}
