//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class ManageProfile
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Button btnTabUpdate;
        protected global::System.Web.UI.WebControls.Button btnTabDeactivateProfile;
        protected global::System.Web.UI.WebControls.Button btnTabDeactivateAccount;
        protected global::System.Web.UI.WebControls.Panel pnlUpdateProfile;
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtContactNumber;
        protected global::System.Web.UI.WebControls.Panel pnlFreelancerFields;
        protected global::System.Web.UI.WebControls.TextBox txtUpdateSkills;
        protected global::System.Web.UI.WebControls.TextBox txtUpdateExperience;
        protected global::System.Web.UI.WebControls.TextBox txtUpdatePortfolio;
        protected global::System.Web.UI.WebControls.TextBox txtUpdateRate;
        protected global::System.Web.UI.WebControls.Panel pnlEmployerFields;
        protected global::System.Web.UI.WebControls.TextBox txtUpdateCompanyName;
        protected global::System.Web.UI.WebControls.DropDownList ddlUpdateIndustry;
        protected global::System.Web.UI.WebControls.TextBox txtUpdateDescription;
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
        protected global::System.Web.UI.WebControls.Panel pnlDeactivateProfile;
        protected global::System.Web.UI.WebControls.CheckBox chkConfirmDeactivateProfile;
        protected global::System.Web.UI.WebControls.Button btnDeactivateProfile;
        protected global::System.Web.UI.WebControls.Panel pnlDeactivateAccount;
        protected global::System.Web.UI.WebControls.CheckBox chkConfirmDeactivateAccount;
        protected global::System.Web.UI.WebControls.Button btnDeactivateAccount;
    }
}
