//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class ReviewProposal
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblReviewMessage;
        protected global::System.Web.UI.WebControls.Label lblFreelancerInitials;
        protected global::System.Web.UI.WebControls.Label lblFreelancerName;
        protected global::System.Web.UI.WebControls.Label lblProjectTitle;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Label lblRate;
        protected global::System.Web.UI.WebControls.Label lblTime;
        protected global::System.Web.UI.WebControls.Label lblDate;
        protected global::System.Web.UI.WebControls.Label lblCoverLetter;
        protected global::System.Web.UI.WebControls.Panel pnlActions;
        protected global::System.Web.UI.WebControls.Button btnApproveProposal;
        protected global::System.Web.UI.WebControls.Button btnRejectProposal;
        protected global::System.Web.UI.WebControls.Button btnBackToProposals;
    }
}
