//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class SelectProposal
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblProposalMessage;
        protected global::System.Web.UI.WebControls.Panel pnlNoProposals;
        protected global::System.Web.UI.WebControls.Repeater rptProposals;
    }
}
