//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class Site1
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlEmployerNav;
        protected global::System.Web.UI.WebControls.Panel pnlLoggedInNav;
        protected global::System.Web.UI.WebControls.Panel pnlGuestButtons;
        protected global::System.Web.UI.WebControls.Panel pnlUserButtons;
        protected global::System.Web.UI.WebControls.Literal litInitials;
        protected global::System.Web.UI.WebControls.Literal litFullName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
