//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class SubmitProposal
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblProjectTitle;
        protected global::System.Web.UI.WebControls.Label lblProjectBudget;
        protected global::System.Web.UI.WebControls.Label lblProjectDeadline;
        protected global::System.Web.UI.WebControls.Label lblProjectCategory;
        protected global::System.Web.UI.WebControls.TextBox txtCoverLetter;
        protected global::System.Web.UI.WebControls.TextBox txtProposedRate;
        protected global::System.Web.UI.WebControls.TextBox txtCompletionTime;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Button btnSubmitProposal;
    }
}
