//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class SwitchRole
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblCurrentRole;
        protected global::System.Web.UI.WebControls.Button btnSwitchFreelancer;
        protected global::System.Web.UI.WebControls.Button btnSwitchEmployer;
        protected global::System.Web.UI.WebControls.Button btnConfirmCreateFreelancer;
        protected global::System.Web.UI.WebControls.Button btnConfirmCreateEmployer;
        protected global::System.Web.UI.WebControls.Button btnConfirmReactivateFreelancer;
        protected global::System.Web.UI.WebControls.Button btnConfirmReactivateEmployer;
    }
}
