//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class SwitchRole
    {
        protected global::System.Web.UI.WebControls.Literal litCurrentIcon;
        protected global::System.Web.UI.WebControls.Literal litCurrentRole;
        protected global::System.Web.UI.WebControls.Literal litCurrentDesc;
        protected global::System.Web.UI.WebControls.Literal litOtherIcon;
        protected global::System.Web.UI.WebControls.Literal litOtherRole;
        protected global::System.Web.UI.WebControls.Literal litOtherDesc;
        protected global::System.Web.UI.WebControls.Literal litOtherStatus;
        protected global::System.Web.UI.WebControls.Button btnSwitch;
        protected global::System.Web.UI.WebControls.Button btnConfirmReactivate;
        protected global::System.Web.UI.WebControls.Button btnConfirmCreate;
    }
}
