//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeHubProject
{
    public partial class ViewProfile
    {
        protected global::System.Web.UI.WebControls.Panel pnlProfile;
        protected global::System.Web.UI.WebControls.Label lblInitials;
        protected global::System.Web.UI.WebControls.Label lblFullName;
        protected global::System.Web.UI.WebControls.Label lblUserType;
        protected global::System.Web.UI.WebControls.Label lblDateJoined;
        protected global::System.Web.UI.WebControls.Label lblRating;
        protected global::System.Web.UI.WebControls.Panel pnlFreelancerInfo;
        protected global::System.Web.UI.WebControls.Label lblSkills;
        protected global::System.Web.UI.WebControls.Label lblExperience;
        protected global::System.Web.UI.WebControls.Label lblRate;
        protected global::System.Web.UI.WebControls.Panel pnlEmployerInfo;
        protected global::System.Web.UI.WebControls.Label lblCompany;
        protected global::System.Web.UI.WebControls.Label lblIndustry;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.Label lblError;
    }
}
